apiVersion: v1
kind: Service
metadata:
  name: project-1-service
spec:
  type: NodePort
  selector:
    app: project-1
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30080
